import numpy as np
calorie_stats = np.genfromtxt('cereal.csv', delimiter=',')
print(calorie_stats)
average_calories = np.mean(calorie_stats) - 60
print(average_calories)
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)
print(np.percentile(calorie_stats, 25))
print(np.percentile(calorie_stats, 10))
print(np.percentile(calorie_stats, 3))
print(len(calorie_stats))
median_calories = np.percentile(calorie_stats, 50)
print(median_calories)
nth_percentile = 3
more_calories = np.mean(calorie_stats > 60)
print(more_calories)
mean_calories = np.mean(calorie_stats)
calorie_std = np.std(calorie_stats)
print("mean:", mean_calories)
print("standard deviation", calorie_std)
print()
print("The data analysis showed that the average calorie count of cereals in the dataset is significantly higher than the 60 calories per serving in CrunchieMunchies. The majority of cereals contained more than 60 calories, showing that CrunchieMunchies is a lower-calorie option compared to most competitors. The standard deviation also showed that while calorie counts vary across cereals, many are still centered around a much higher average. Yummy Corp could use these findings in marketing by promoting CrunchieMunchies as a healthier and lighter cereal choice for consumers who want lower-calorie breakfast options.")